name: FShootingGame
version: '1.0-SNAPSHOT'
main: com.fretka46.fShootingGame.FShootingGame
api-version: '1.21'
author: "fretka46"
description: A shooting game plugin for Minecraft

softdepend: ["PlaceholderAPI"]
